

// TOMEM CUIDADO, UMA VIRGULA, ATÉ UM ACENTO ERRADO PODE CAUSAR ERRO, SALVE ANTES DE ALTERAR PARA EVITAR PROBLEMAS.

const TEXTOS_GERAL =  {

MENSAGEM_DE_SO_USAR_EM_GRUPO: `🫵🏻 Ô seu fresquinho este comando só deve ser utilizado em grupos, rala daqui pnc do carai 🖕🏿🤬`,

MENSAGEM_DE_SO_DONO_USAR_COMANDOS: `🫵🏻 Epá! este comando é apenas para o meu dono utilizar 🤦🏻`,

MENSAGEM_DE_SO_ADM_CONSEGUIR_USAR_X_COMANDO: `🫵🏻 Epá! somente Admin pode utilizar este comando, se ferrou.😝`,

MENSAGEM_DE_QUANDO_O_BOT_NAO_E_ADM: `🫵🏻 Ô Bot precisa ser Admiro do grupo para utilizar este comando.🫡`,

// O #prefixo# é padrão para mostrar o prefixo do bot.

MENSAGEM_DE_SO_QUANDO_MODO_BRINCADEIRA_FOR_ATIVO: `Este comando so pode ser utilizado com o comando #prefixo#modobrincadeira ativado, para desativar só basta usar o comando novamente 🥱`,

MENSAGENS_DE_AGUARDE: ["🚀 Segura aí que o Scheyot tá carregando os pacotes, quase online 🔥",
  "🎶 ‘Calma, neném, daqui a pouco nós desenrola…’ ⏳",
  "😎 Josival disse: quem espera sempre alcança, então relaxa 🍃",
  "🖥️ Rafael tá no teclado insano configurando a máq… já já sai 💻",
  "👩‍💻 Luana tá digitando mais rápido que bot do zap ⚡",
  "💡 Dev Gui tá testando a API, calma que já conecta!",
  "🌍 bronxyshost.com — maior site de hospedagem do BR, só máquina braba 🔥",
  "📡 Conexão em andamento… quase lá, confia 🤙",
  "😂 ‘O pai tá on’, mas o bot ainda tá aquecendo… segura 🔋",
  "🥶 Se tá frio, imagina esperar o bot… segura que já já vem 🔥",
  "🎧 Enquanto espera, lembra: ‘quem mandou tu terminar comigo…’ 🎶",
  "⚙️ Upload 99%… só não cai igual download de madrugada kkk 📲",
  "👾 Bot do BronxysHost aquecendo os motores, segura ✈️",
  "🚦 Pera aí, o sinal abriu mas a API tá atravessando ainda 🛑",
  "📀 Scheyot falou: ‘aguarde só mais um hit e já volto’ 🎶",
  "🤯 ‘Na quebrada nós é destaque’… já já seu bot também 💥",
  "🍕 Enquanto isso, pede um lanche e relaxa, daqui a pouco responde 😋",
  "🔥 BronxysHost.com — onde até o aguarde é turbo ⚡",
  "😂 ‘É os guri, fio’… segura que já já chega a resposta 🕶️",
  "🐊 Tempo de espera quase zero, estilo corre do Dev Gui 🏎️",
  "🎮 Carregando igual tela de GTA… só mais um pouco 🎲",
  "👻 Até o Josival sumiu no delay… mas calma, volta já 👀",
  "📀 ‘Deixa acontecer naturalmente’ enquanto o bot responde 🎶",
  "🏆 Rafael tá otimizando, porque aqui só troféu de melhor host 🥇",
  "🕶️ Luana deixou no ponto, falta só rodar o script 🔄",
  "💭 Enquanto isso, pensa em como a BronxysHost sustenta o game 🤯",
  "🚀 Scheyot ativou o modo foguete, só aguardar 🛰️",
  "🥤 Pega um refri e relaxa, o bot vem logo 🍹",
  "📡 BronxysHost.com — até seu aguarde é premium 🔝",
  "🎲 O jogo tá carregando… segura a emoção 🕹️",
  "🖤 ‘Bot on, coração tranquilo’ 🕊️",
  "💿 Configuração rodando em vinil… suave, mas chega 🎧",
  "🔥 Dev Gui nunca falha, só dá um tempo ⚡",
  "😅 Até bug precisa de intervalo… segura aí!",
  "🚗 A API tá no trânsito, já estaciona aí 🅿️",
  "🛸 BronxysHost pilotando a nave, já já pousa 👨‍🚀",
  "😂 ‘Se tu não aguenta esperar, imagina casar’ 💍",
  "📲 Rafael tá mandando pacotes como se fosse figurinha 😆",
  "💡 Luana iluminou os servidores, só brilha 💡",
  "🎤 ‘No aguardo, tipo show do trap atrasado’ 🎶",
  "🍿 Aproveita e pega uma pipoca, tá quase pronto 🎥",
  "🤖 BronxysHost — aqui até o delay é estiloso 👑",
  "⚡ Scheyot energizou o servidor, segura a carga 🔋",
  "🐢 Dev Gui ativou o modo tartaruga, mas só por uns segundos 🐢",
  "🚦 API esperando o sinal verde… calma ✋",
  "🎧 ‘Enquanto espero, só ouço trap do BronxysHost’ 🎶",
  "🔥 Josival jogou gasolina no código, tá voando 🚒",
  "😂 Até a Luana disse: ‘calma fio, já vem’ 🕊️",
  "🎲 Loading 80%… só não fecha o app agora 🙏",
  "🕶️ BronxysHost — o bonde das APIs sem limite 🚀",
  "🤯 Se esperar fosse crime, já taria preso kkk 🚔",
  "🍕 Scheyot pediu pizza, chega antes que a resposta? 👀",
  "📡 O servidor tá viajando no espaço… já retorna 🌌",
  "😂 ‘Aguenta coração, que a API tá vindo’ 💓",
  "💻 Rafael compila mais rápido que o Flash ⚡",
  "👑 BronxysHost é rei, até no ‘aguarde’ tem estilo 👑",
  "🕊️ Luana mandou avisar: já já é GG ✨",
  "⚙️ Dev Gui tá montando engrenagem por engrenagem 🔩",
  "🎶 ‘Eu só quero é ser feliz… e esse bot responder’ 🎵",
  "🍹 Pega um suco, porque sede a gente mata, mas resposta demora 😅",
  "🚀 Josival abriu a cápsula… pronto pra decolar!",
  "🎤 BronxysHost — flow até no delay 🎶",
  "🖥️ Scheyot programando no modo insano 🧑‍💻",
  "⚡ ‘Se cair, nós sobe de novo’… confia 💪",
  "🤖 Dev Gui disse: tempo de resposta menor que sua internet 👀",
  "🌎 BronxysHost.com — servidor mundial 🌐",
  "😂 Rafael disse: segura que é na pressão 🔥",
  "🎲 Carregando igual combo no Street Fighter 🎮",
  "🕶️ Luana estilosa, só manda quando tá pronto 🖤",
  "📲 ‘Aguarde… mas não sofra’ 🥹",
  "🚦 Esperar também é game… confia 🎮",
  "👻 BronxysHost — fantasma no tempo de delay 👻",
  "💡 Scheyot brilhando na tela de log 🤩",
  "🔥 Dev Gui faz mágica até no aguarde 🪄",
  "🍿 Relaxa, tá no forno 🍞",
  "🕊️ Josival voando nos servidores ☁️",
  "⚙️ Rafael trocando a marcha do bot 🏎️",
  "🎧 ‘O pai tá diferente’… mas responde já já 🎶",
  "🚀 BronxysHost, foguete não dá ré 🚀",
  "😂 Luana disse: segura que é só um café ☕",
  "📀 Scheyot trocando o disco, já já toca outra 🎧",
  "🐍 Delay tá andando de cobra, mas chega 🐍",
  "👑 BronxysHost rei dos bots 👑",
  "🕶️ ‘Enquanto isso, só paz e love’ 💌",
  "⚡ API turbo no carregamento 🔋",
  "🚦 Se tá no vermelho, já já fica verde 💚",
  "🎤 Dev Gui: flow até no debug 🎤",
  "🍹 Relaxa, senta e espera 🍸",
  "🔥 BronxysHost faz valer cada segundo 🔥",
  "🖥️ Rafael mexendo no código, tipo DJ 🎚️",
  "😂 ‘Calma bebê, daqui a pouco responde’ 🍼",
  "🕊️ Luana mandou avisar: segura a emoção ✨",
  "🎲 Loading infinito? Não, só parece 😆",
  "⚙️ Scheyot apertando parafusos no server 🔩",
  "📀 BronxysHost rodando suave, tipo vinil 🎶",
  "🌍 Delay global, mas a resposta é local 🌐",
  "🎤 Josival rimando até no log 🎤",
  "🚀 O bot tá decolando… só mais 3…2…1 🚀",
  "🍕 BronxysHost entrega mais rápido que motoboy 🛵",
  "😂 Rafael testando e rindo do delay 🤣",
  "🕶️ Luana no comando, calma aí 😎",
  "⚡ Dev Gui ligou o turbo 💨",
  "🎶 Enquanto carrega, canta comigo: ‘tá tranquilo, tá favorável’ 🎶",
  "👑 BronxysHost sempre no topo 👑",
  "🚦 Sinal amarelo: atenção, já vai! 🟡",
  "🐊 Delay crocodilo, mas devora logo 🐊",
  "🔥 Scheyot na febre do código 🔥",
  "🕊️ BronxysHost voando sem asa ✈️",
  "🍿 Josival disse: só mais um trailer 🎬",
  "🎧 Rafael dropando beat na API 🎶",
  "⚙️ Dev Gui calibrando servidor 🔧",
  "📲 Luana no Whats mandou: ‘seguraaa’ 📩",
  "😂 ‘Tempo é dinheiro, mas a BronxysHost paga com resposta’ 💸",
  "🚀 BronxysHost sempre no futuro 🚀",
  "🖥️ Scheyot hackeando o próprio delay 👨‍💻",
  "🌎 Global, mas sempre rápido 🌐",
  "🎶 ‘Deixa rolar, deixa rolar…’ 🎶",
  "🍹 Delay com gelo, mas passa suave 🥶",
  "⚡ Rafael ativou modo flash ⚡",
  "🔥 BronxysHost — on fire sempre 🔥",
  "👑 Luana rainha do log 👑",
  "😂 Josival: ‘só mais 5 segundinho, juro’ 😆",
  "🎲 Loading 101% (bug visual, mas quase) 🎮",
  "🚦 Dev Gui ajustando rota 🛣️",
  "📡 BronxysHost conectando satélite 🚀",
  "🎧 Scheyot no beat e no código 🎶",
  "🐍 Delay só enrola, mas vem 🐍",
  "🔥 Rafael dropa código como trapper dropa verso 🎤",
  "🕊️ BronxysHost paz e resposta ✨",
  "😂 ‘Calma, calma, calma, respira’ 😮‍💨",
  "🍕 Enquanto isso, pede um delivery 🛵",
  "⚡ Dev Gui sempre no 220v 🔋",
  "👑 BronxysHost maior que todos 👑",
  "🚀 Scheyot ativou modo turbo 🚀",
  "🎶 ‘Esperando o zap, mas o flow não para’ 🎵",
  "🍿 Delay virou cinema 🍿",
  "🕶️ Luana sempre online 👩‍💻",
  "😂 Josival sumiu no aguarde, mas já volta 👀",
  "🎲 Loading que nunca decepciona 🎮",
  "🔥 BronxysHost — só máquina 🔥",
  "⚙️ Rafael trocando o engine do bot 🛠️",
  "🚦 Delay no farol vermelho 🚨",
  "👑 Dev Gui imperador da API 👑",
  "🎧 BronxysHost rimando com progresso 🎤",
  "🖥️ Scheyot mais rápido que script malicioso 🐱‍💻",
  "😂 ‘Tá demorando? Relaxa, já já vai’ 🕰️",
  "🌎 BronxysHost.com dominando o BR 🌐",
  "🎲 Loading infinito mode on 🎮",
  "🍹 Luana recarregando com café ☕",
  "🔥 Rafael energizando o host 🔥",
  "⚡ Dev Gui sempre pronto ⚡",
  "👑 BronxysHost, onde até o delay é chique 👑",
  "🚀 Scheyot botando foguete no servidor 🛰️",
  "😂 ‘Segura bebê, já vem’ 🍼",
  "🎶 ‘Só os loucos sabem’… esperar também 🎶",
  "🕶️ Josival estiloso até no log 😎",
  "🍿 BronxysHost no cinema da espera 🎬",
  "📡 Rafael subindo pro satélite 🚀",
  "🔥 Dev Gui dropando código 🔥",
  "⚙️ BronxysHost no controle total 🛠️",
  "🎧 Scheyot DJ do servidor 🎶",
  "😂 ‘Aguenta coração’ 💔",
  "🚦 Delay, mas já vem 🌟",
  "🕶️ Luana tranquilona no aguarde 😎",
  "🍹 BronxysHost drink premium do host 🍸",
  "🔥 Rafael turbo ⚡",
  "⚡ Dev Gui só sucesso ⚡",
  "👑 BronxysHost rei do Brasil 👑",
  "🎶 ‘Esperando resposta, tipo fã em show’ 🎶",
  "🚀 Scheyot voando 🚀",
  "😂 Josival rindo do lag 🤣",
  "🍿 BronxysHost delivery rápido 🛵",
  "🖥️ Rafael afiado no teclado 💻",
  "⚙️ Dev Gui montando API 🛠️",
  "🎧 BronxysHost sempre no ritmo 🎶",
  "🔥 Luana na energia 🔥",
  "👑 BronxysHost supremo 👑",
  "😂 Delay comédia kkk 🤣",
  "🚦 Loading, loading… loading 🛑",
  "🍹 BronxysHost geladinho 🍸",
  "⚡ Rafael ativou modo rápido ⚡",
  "🔥 BronxysHost 🔥",
  "👑 Scheyot rei da madrugada 👑",
  "🕶️ Dev Gui blindado 🕶️",
  "🎶 BronxysHost sempre no beat 🎧",
  "🚀 Luana foguete sem ré 🚀",
  "😂 Josival e o tempo kkk 😆",
  "🍿 BronxysHost cinema infinito 🎬",
  "⚙️ Rafael no conserto rápido 🛠️",
  "🔥 Dev Gui sem bug 🔥",
  "👑 BronxysHost total 👑",
  "🎶 Scheyot cantando no servidor 🎤",
  "🚀 Delay turbo 🚀",
  "🕶️ BronxysHost só luxo 🕶️",
  "🍹 Rafael no cafezinho ☕",
  "⚡ BronxysHost sem freio ⚡",
  "🔥 Luana on fire 🔥",
  "👑 Josival no comando 👑",
  "😂 Delay engraçado 🤣",
  "🚦 BronxysHost semáforo verde 🟢",
  "🍿 BronxysHost pipoca premium 🍿",
  "⚙️ Dev Gui sempre no código 🛠️",
  "🔥 Rafael dropa script 🔥",
  "🎶 BronxysHost trap tech 🎶",
  "🚀 Scheyot pilotando host 🚀",
  "🕶️ BronxysHost com estilo 🕶️",
  "🍹 Delay refrescante 🍹",
  "⚡ Luana carregando ⚡",
  "👑 BronxysHost master 👑",
  "😂 Josival doidão no log 🤣",
  "🎧 BronxysHost mixtape tech 🎧",
  "🔥 Rafael energizado 🔥",
  "🚦 Dev Gui sem demora 🚦",
  "🍿 BronxysHost session 🎬",
  "⚡ Scheyot veloz ⚡",
  "👑 BronxysHost supremo 👑"],

// LINK DA IMAGEM DO COMANDO DE CASAL
LINK_COMANDO_CASAL: "https://xatimg.com/image/K88c2BkQwlcF.jpg",

// TEXTO DO COMANDO DE CASAL // O #porcentagem# vai puxar de 0 a 100.
TEXTO_COMANDO_CASAL: `🌟 Casal do grupo com ॐ #porcentagem# ✨ de chance pra da certo 😏:`,

// PALAVRAS QUE SÃO PROIBIDAS DO SIMIH FALAR.
PALAVRAS_PROIBIDA_DE_O_SIMI_FALAR: ["porra", "carai", "caralho", "buceta", "bct", "teu cu","meu pau", "minha chibata", "pika", "seu cu", "sexo", "gozar", "gozei"],

COMANDO_BAN_MENSAGEM: `#usuario# 𝘾𝘼𝙄 𝙁𝙊𝙍𝘼 🏌🏻‍♂️`,

COMANDO_PROMOVEU_MENSAGEM:`#usuario# Foi promovido para adm, agora bora mostrar serviços 🤦`,

COMANDO_REBAIXOU_MENSAGEM: `#usuario# Foi Rebaixado para [ MEMBRO COMUM ] Chora não, Coleguinha 🥹`,

// QUISER QUE O ANTI LINK, ENVIE MENSAGEM, SÓ MUDAR O 0 PARA A MENSAGEM DE REMOÇÃO, OU ENTÃO, DEIXA 0, SE QUISER DEIXAR SEM MENSAGEM, SÓ VOLTAR PRO 0 DENOVO.
TEXTO_REMOCAO_ANTI_LINK: `🤺_𝘼𝙦𝙪𝙞 𝙣𝙖‌𝙤 𝙥𝙤𝙙𝙚 𝙢𝙖𝙣𝙙𝙖𝙧 ~(𝗟𝗜𝗡𝗞𝘀)~ 𝙣𝙖‌𝙤 𝙡𝙚𝙪 𝙖𝙨 𝙍𝙚𝙜𝙧𝙖𝙨 🤔`,

LIMITE_CARACTERES_MSG: '🏌🏻‍♂️_𝙑𝙖𝙯𝙖 𝙙𝙖𝙦𝙪𝙞 𝘾𝙖𝙧𝙣𝙞𝙘̧𝙖!  𝙇𝙚𝙧 𝙖 𝙥𝙤𝙧𝙧𝙖 𝙙𝙖𝙨 𝙍𝙚𝙜𝙧𝙖𝙨  𝙦𝙪𝙖𝙣𝙙𝙤 𝙚𝙣𝙩𝙧𝙖𝙧 𝙚𝙢 𝙂𝙧𝙪𝙥𝙤𝙨_🤺',

LISTA_NEGRA_GLOBAL_MENSAGEM: '🫵🏻 𝙊𝙡𝙝𝙖 𝙦𝙪𝙚𝙢 𝙙𝙚𝙪 𝙖𝙨 𝘾𝙖𝙧𝙖𝙨 𝙥𝙤𝙧 𝙖𝙦𝙪𝙞.  𝘼𝙦𝙪𝙞 𝙫𝙤𝙘𝙚̂ 𝙣𝙖̃𝙤 𝙫𝙖𝙞 𝙗𝙖𝙜𝙪𝙣𝙘̧𝙖 𝙣𝙖̃𝙤!  𝙎𝙞𝙣𝙩𝙖 𝙤 𝙥𝙤𝙙𝙚𝙧 𝙙𝙤 𝘽𝙖𝙣 🤬\n🤺_𝗩𝗔𝗭𝗔 𝗖𝗔𝗕𝗔𝗖̧𝗢_🏌',

MENSAGEM_GRUPO_ABRIU: "🚨>𝗚𝗥𝗨𝗣𝗢 𝗔𝗕𝗘𝗥𝗧𝗢<🚨\n𝘽𝙤𝙧𝙖 𝙛𝙤𝙛𝙤𝙘𝙖𝙧 𝙜𝙖𝙡𝙚𝙧𝙖 𝙛𝙖𝙡𝙖𝙧 𝙙𝙖 𝙫𝙞𝙙𝙖 𝙙𝙤𝙨 𝙫𝙞𝙯𝙞𝙣𝙝𝙤𝙨 😏",

MENSAGEM_GRUPO_FECHOU: "❌𝗚𝗥𝗨𝗣𝗢 𝗙𝗘𝗖𝗛𝗔𝗗𝗢❌\n𝙋𝙤𝙧 𝙝𝙤𝙟𝙚 𝙗𝙖𝙨𝙩𝙖, 𝙨𝙚𝙪𝙨 𝙛𝙤𝙛𝙤𝙦𝙪𝙚𝙞𝙧𝙤𝙨 𝙫𝙖̃𝙤 𝙙𝙤𝙧𝙢𝙞𝙧 𝙖𝙩𝙚́ 𝙖𝙢𝙖𝙣𝙝𝙖̃ 🥱",

}

exports.TEXTOS_GERAL = TEXTOS_GERAL;